version: 2.1

executors:
  python3:
    docker:
      - image: circleci/python:3.8

commands:
  build:
    parameters:
      version:
        type: string
    steps:
      - run:
          name: Building package
          command: |
            python3 -m pip install -U setuptools wheel twine
            export PACKAGE_VERSION="<< parameters.version >>"
            python3 setup.py sdist bdist_wheel
            python3 -m twine check dist/*
  publish:
    parameters:
      repository:
        type: enum
        enum: ["pypi", "testpypi"]
        default: "pypi"
      token:
        type: string
    steps:
      - run:
          name: Publishing package
          command: |
            export TWINE_REPOSITORY="<< parameters.repository >>"
            export TWINE_USERNAME="__token__"
            export TWINE_PASSWORD="<< parameters.token >>"
            python3 -m twine upload --non-interactive dist/*

jobs:
  test:
    docker:
      - image: themattrix/tox
    steps:
      - run:
          name: Installing required tools
          command: apt update && apt install -y git ssh tar gzip ca-certificates
      - checkout
      - run:
          name: Running tests
          command: tox
  test-build:
    executor: python3
    steps:
      - checkout
      - build:
          version: "0.0.0"
  test-publish:
    executor: python3
    steps:
      - checkout
      - build:
          version: "${CIRCLE_TAG:1}.dev`date -u '+%Y%m%d%H%M%S'`"
      - publish:
          repository: testpypi
          token: "${TEST_PYPI_TOKEN}"
  publish:
    executor: python3
    steps:
      - checkout
      - build:
          version: "${CIRCLE_TAG:1}"
      - publish:
          token: "${PYPI_TOKEN}"

workflows:
  version: 2
  test:
    jobs:
      - test
      - test-build
  publish:
    when:
      matches:
        pattern: '^v[0-9]+(\.[0-9]+){2}$'
        value: << pipeline.git.tag >>
    jobs:
      - test
      - test-publish:
          requires:
            - test
      - hold:
          type: approval
          requires:
            - test
      - publish:
          requires:
            - hold
