version: 2.1

executors:
  python3:
    docker:
      - image: circleci/python:3.8

commands:
  publish:
    parameters:
      repository:
        type: enum
        enum: ["pypi", "testpypi"]
        default: "pypi"
      token:
        type: string
      version:
        type: string
    steps:
      - run:
          name: Publishing package
          command: |
            python3 -m pip install -U setuptools wheel twine
            export PACKAGE_VERSION="<< parameters.version >>"
            python3 setup.py sdist bdist_wheel
            python3 -m twine check dist/*
            export TWINE_REPOSITORY="<< parameters.repository >>"
            export TWINE_USERNAME="__token__"
            export TWINE_PASSWORD="<< parameters.token >>"
            python3 -m twine upload --non-interactive dist/*

jobs:
  test:
    docker:
      - image: themattrix/tox
    steps:
      - run:
          name: Installing required tools
          command: apt update && apt install -y git ssh tar gzip ca-certificates
      - checkout
      - run:
          name: Running tests
          command: tox
  test-publish:
    executor: python3
    steps:
      - checkout
      - publish:
          repository: testpypi
          token: "${TEST_PYPI_TOKEN}"
          version: "${CIRCLE_TAG:1}.dev`date -u '+%Y%m%d%H%M%S'`"
  publish:
    executor: python3
    steps:
      - checkout
      - publish:
          token: "${PYPI_TOKEN}"
          version: "${CIRCLE_TAG:1}"

workflows:
  version: 2
  test-and-publish:
    jobs:
      - test:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+){2}/
      - test-publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - publish:
          requires:
            - hold
          filters:
            tags:
              only: /.*/
